library(matrixcalc)
library(mnormt)
library(igraph)
library(rlist)
library(Rcpp)
library(parallel)
library(magrittr)
library(dplyr)
library(RColorBrewer)
library(nnet)  #to select the max QI at random when there is a tie
library(randomcoloR)
library(aniSNA)
library(assortnet)
